# Generated by Django 5.1.2 on 2025-05-22 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=100)),
                ('Pago', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.CharField(max_length=100)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Numero', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Puesto', models.CharField(max_length=100)),
                ('Edad', models.CharField(max_length=100)),
                ('Nacionalidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreMetodo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ubicacion', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Equipos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProximosEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventos', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('Contrasena', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BiografiaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=100)),
                ('Jugadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BiografiaJugador', to='api.jugadores')),
            ],
        ),
        migrations.CreateModel(
            name='LocalidadDetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DetalleVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LocalidadDetalleVenta', to='api.detalleventa')),
                ('Localidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LocalidadDetalleVenta', to='api.localidades')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='Localidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DetalleVenta', to='api.localidades'),
        ),
        migrations.CreateModel(
            name='UltimosResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resultado', models.CharField(max_length=100)),
                ('Partidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UltimosResultados', to='api.partidos')),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Membresia', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio_Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Boleteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Venta', to='api.boleteria')),
                ('DetalleVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Venta', to='api.detalleventa')),
                ('MetodosPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Venta', to='api.metodospago')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Venta', to='api.usuario')),
            ],
        ),
    ]
