# Generated by Django 5.1.2 on 2025-05-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biografiajugador',
            old_name='Descripcion',
            new_name='Club_Actual',
        ),
        migrations.RenameField(
            model_name='jugadores',
            old_name='Apellido',
            new_name='Nombre_Completo',
        ),
        migrations.RenameField(
            model_name='jugadores',
            old_name='Edad',
            new_name='Posicion',
        ),
        migrations.RemoveField(
            model_name='jugadores',
            name='Nacionalidad',
        ),
        migrations.RemoveField(
            model_name='jugadores',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='jugadores',
            name='Numero',
        ),
        migrations.RemoveField(
            model_name='jugadores',
            name='Puesto',
        ),
        migrations.AddField(
            model_name='biografiajugador',
            name='Altura',
            field=models.DecimalField(decimal_places=2, default=1.75, max_digits=10),
        ),
        migrations.AddField(
            model_name='biografiajugador',
            name='Edad',
            field=models.CharField(default=20, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biografiajugador',
            name='Fecha_Nacimiento',
            field=models.DateField(default='2004-05-06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biografiajugador',
            name='Lugar_Nacimiento',
            field=models.CharField(default='Puntarenas', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biografiajugador',
            name='Nacionalidad',
            field=models.CharField(default='Costarricense', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biografiajugador',
            name='Numero',
            field=models.DecimalField(decimal_places=2, default='5', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biografiajugador',
            name='Peso',
            field=models.DecimalField(decimal_places=2, default=75.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biografiajugador',
            name='Pie_Dominante',
            field=models.CharField(default='Derecho', max_length=100),
            preserve_default=False,
        ),
    ]
