# Generated by Django 5.2 on 2025-05-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_boleteria_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='Boleteria',
        ),
        migrations.DeleteModel(
            name='Boleteria',
        ),
    ]
