# Generated by Django 5.1.2 on 2025-05-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_descripcion_biografiajugador_club_actual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biografiajugador',
            name='Jugadores',
        ),
        migrations.AddField(
            model_name='biografiajugador',
            name='Nombre_Completo',
            field=models.CharField(default='Jean Sanchez', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biografiajugador',
            name='Posicion',
            field=models.CharField(default='Defensa', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Jugadores',
        ),
    ]
