# Generated by Django 5.1.2 on 2025-05-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_biografiajugador_jugadores_and_more'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='venta',
        #    name='Boleteria',
        #),
        #
    ]
