# Generated by Django 5.2 on 2025-05-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_biografiajugador_jugadores_and_more'),
        ('api', '0003_remove_venta_boleteria_delete_boleteria'),
    ]

    operations = [
    ]
