# Generated by Django 5.1.2 on 2025-06-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_venta_boleteria_delete_boleteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='biografiajugador',
            name='Imagen',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
