# Generated by Django 5.1.2 on 2025-06-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_biografiajugador_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='proximoseventos',
            name='Imagen',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
