# Generated by Django 5.1.2 on 2025-06-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_proximoseventos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='Boleteria',
        ),
        migrations.AddField(
            model_name='ultimosresultados',
            name='Imagen',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Boleteria',
        ),
    ]
